$font = Iosevka Nerd Font Propo

general {
    hide_cursor = true
}
animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = HDMI-A-3
    path = screenshot
    blur_passes = 4 
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.25) # no fill

    outer_color = rgba(150, 150, 150, 0.5)
    check_color = rgba(100, 200, 100, 0.7)
    fail_color = rgba(200, 100, 100, 0.7)

    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    rounding = 24

    font_family = $font
    placeholder_text = << Password Here >> 
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 100
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, 150
    halign = center
    valign = bottom 
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, 300
    halign = center
    valign = bottom
}

# label {
    # monitor =
    # text = $LAYOUT[en,ru]
    # font_size = 24
    # onclick = hyprctl switchxkblayout all next

    # position = 250, -20
    # halign = center
    # valign = center
# }

